# Generated by Django 5.2 on 2025-04-29 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0004_observacion_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='ejercicios.ejercicio')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ejercicio', to='socios.socio')),
            ],
        ),
    ]
