from django.db import migrations
from datetime import date
from django.utils.timezone import now
from decimal import Decimal, InvalidOperation


def cargar_ejercicios_y_registros(apps, schema_editor):
    Socio = apps.get_model('socios', 'Socio')
    Ejercicio = apps.get_model('ejercicios', 'Ejercicio')
    RegistroEjercicio = apps.get_model('ejercicios', 'RegistroEjercicio')

    hoy = now().date()

    ejercicios_nombres = [
        "SUMO", "ELEVACIONES", "CUADRICEPS", "SENTADILLAS",
        "REMO 1BB", "REMO POLEA", "TRICEPS POLEA", "DORSALES", "PECHO"
    ]

    # Crear ejercicios si no existen
    ejercicios_objetos = {}
    for nombre in ejercicios_nombres:
        ejercicio, creado = Ejercicio.objects.get_or_create(nombre=nombre)
        ejercicios_objetos[nombre] = ejercicio

    # 🔥 Datos duros de socios y pesos (ejemplo)
    SOCIOS_Y_PESOS = [('Aggio Diego',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': None,
    'PECHO': '12',
    'REMO 1BB': '7kg',
    'REMO POLEA': '5',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '4'}),
    ('Albornoz Mari',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Alfano Ariel',
    {'CUADRICEPS': '7',
    'DORSALES': '7',
    'ELEVACIONES': '20',
    'PECHO': '17',
    'REMO 1BB': '7,5',
    'REMO POLEA': '7',
    'SENTADILLAS': '20',
    'SUMO': '15',
    'TRICEPS POLEA': '5'}),
    ('Aliano Ana Laura',
    {'CUADRICEPS': '2',
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Almada Aye',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Alvarez Sol',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '3,5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Amiguetti Pity',
    {'CUADRICEPS': '6',
    'DORSALES': '4',
    'ELEVACIONES': '35',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '17',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Amigutty jose',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': 'rusa',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Amoros Santi',
    {'CUADRICEPS': '6',
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '20',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Arroyo Celeste',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '4',
    'SENTADILLAS': '2,5',
    'SUMO': 'barra',
    'TRICEPS POLEA': '2'}),
    ('Balumbo Lupe',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '4',
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('barbi',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Basso Ines',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Benavides Negro',
    {'CUADRICEPS': '8',
    'DORSALES': '6',
    'ELEVACIONES': None,
    'PECHO': '15',
    'REMO 1BB': '7,5',
    'REMO POLEA': '6',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '5'}),
    ('Benavides Rafa',
    {'CUADRICEPS': '4',
    'DORSALES': '5',
    'ELEVACIONES': None,
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '4'}),
    ('Benitez Jesi',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '20',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '17,5',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Benitez Yesi 2',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Bernardini Cami',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Biscaychipi Mariano',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '25',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Boguetti Gonza',
    {'CUADRICEPS': '5',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '5'}),
    ('Bos Cata',
    {'CUADRICEPS': '6',
    'DORSALES': '3',
    'ELEVACIONES': '30',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Bos Yanina',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Brondo Male',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '4',
    'REMO POLEA': None,
    'SENTADILLAS': '7,5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Bruno Mauro',
    {'CUADRICEPS': '3',
    'DORSALES': '5',
    'ELEVACIONES': '30',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '12',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Bustos Gimena',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Cabrera Euge',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Caloni Nico',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '7,5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Campana Marcela',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Cano Marcela',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Cañete Jose',
    {'CUADRICEPS': '6',
    'DORSALES': '6',
    'ELEVACIONES': '15',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '7',
    'SENTADILLAS': '12',
    'SUMO': '5',
    'TRICEPS POLEA': '6'}),
    ('Carusso Mia',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': None,
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': 'rusa',
    'TRICEPS POLEA': '3'}),
    ('Cassini Ro',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Castro Nico',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '4',
    'REMO POLEA': '2',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Cejas Vanesa',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Centioli Mari',
    {'CUADRICEPS': '3-4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': 'rusa',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Conte Mariano',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '20',
    'PECHO': '10',
    'REMO 1BB': '7,5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Coronel Sil',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '7',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Cristian Loriega',
    {'CUADRICEPS': None,
    'DORSALES': '4',
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': '5',
    'TRICEPS POLEA': None}),
    ('Curci Juli',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '20',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '12',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Curti Valentina',
    {'CUADRICEPS': '2',
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '2',
    'REMO POLEA': '2',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Dandrilli dani',
    {'CUADRICEPS': '5',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '12',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Diaz Rosario',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Diz Juli',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '4',
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Dominguez Vale',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Dufayard ale',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '25',
    'PECHO': '7,5',
    'REMO 1BB': '6',
    'REMO POLEA': '6',
    'SENTADILLAS': '17',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Dumanski Cristina',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Echegaray Moni',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5,0',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Edu',
    {'CUADRICEPS': '8',
    'DORSALES': '6',
    'ELEVACIONES': None,
    'PECHO': '15',
    'REMO 1BB': '7,5',
    'REMO POLEA': '6',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '5'}),
    ('Eggs Rocio',
    {'CUADRICEPS': '5',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '12,5',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Erbacci Lujan',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Espil Juli',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Etchebere Mechi',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Fardauz Lucas',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Fernandez Graciela',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Ferraz Oriana',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '1',
    'REMO 1BB': '5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Figiolo Fran',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '7,5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Figiolo Sol',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': '20',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': '',
    'TRICEPS POLEA': None}),
    ('Forni Anto',
    {'CUADRICEPS': '8',
    'DORSALES': '5',
    'ELEVACIONES': '35',
    'PECHO': '10',
    'REMO 1BB': '6',
    'REMO POLEA': '4',
    'SENTADILLAS': '17,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Furiati Ana',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '4',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Gaitan Mariana',
    {'CUADRICEPS': '2',
    'DORSALES': '1',
    'ELEVACIONES': '5',
    'PECHO': 'barra',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '1'}),
    ('gallegos leo',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '25',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Gamero rosana',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': 'disco',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Garau Lili',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Garcia Cooper Jose',
    {'CUADRICEPS': '6',
    'DORSALES': '6',
    'ELEVACIONES': '20',
    'PECHO': '15',
    'REMO 1BB': '7,5',
    'REMO POLEA': '6',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '6'}),
    ('Gasparini Pilar',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Geretto Curi',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Giachino Mari luz',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': 'barra',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Gomez Nati',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '20',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Gonzale Brian',
    {'CUADRICEPS': '7',
    'DORSALES': '8',
    'ELEVACIONES': '30',
    'PECHO': '15',
    'REMO 1BB': '10',
    'REMO POLEA': '8',
    'SENTADILLAS': '20',
    'SUMO': '15',
    'TRICEPS POLEA': '6'}),
    ('Gonzalez Estefania',
    {'CUADRICEPS': '2',
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': '2',
    'SENTADILLAS': 'barra',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Gonzalez Fabi',
    {'CUADRICEPS': '5',
    'DORSALES': '5',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '6',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Gorosito Vir',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Guarino Valen',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': 'barra',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': 'barra',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Haydee Scorzato',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Hever Ceci',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Ibarbuden Cami',
    {'CUADRICEPS': '8',
    'DORSALES': '4',
    'ELEVACIONES': '5',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '12',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Kuchta Agus',
    {'CUADRICEPS': '7',
    'DORSALES': '3',
    'ELEVACIONES': '25',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Kuchta Lara',
    {'CUADRICEPS': '7',
    'DORSALES': '3',
    'ELEVACIONES': '30',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('laclotte carla',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Laclotte May',
    {'CUADRICEPS': '6',
    'DORSALES': '4',
    'ELEVACIONES': '25',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Ledesma Matias',
    {'CUADRICEPS': '5',
    'DORSALES': '5',
    'ELEVACIONES': '15',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Lettiere Anto',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Lombardo Nati',
    {'CUADRICEPS': '2',
    'DORSALES': None,
    'ELEVACIONES': '5',
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Lopez Lara',
    {'CUADRICEPS': '4',
    'DORSALES': None,
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': None}),
    ('Lopez Sergio',
    {'CUADRICEPS': '7',
    'DORSALES': '6',
    'ELEVACIONES': '25',
    'PECHO': '20',
    'REMO 1BB': '7,5',
    'REMO POLEA': '8',
    'SENTADILLAS': '12',
    'SUMO': None,
    'TRICEPS POLEA': '6'}),
    ('Luccon igna',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '12',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Luchetti vir',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Luciaw Mari',
    {'CUADRICEPS': '5',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '10',
    'TRICEPS POLEA': '2'}),
    ('Mancuso Tere',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Marazzo Agos',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '20',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Marczewuski Vale',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': '20',
    'PECHO': '10',
    'REMO 1BB': '12',
    'REMO POLEA': None,
    'SENTADILLAS': '15',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Mariñelarena Zulma',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Martin Flor',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': 'barra',
    'TRICEPS POLEA': '3'}),
    ('Martini Omar',
    {'CUADRICEPS': '6',
    'DORSALES': '6',
    'ELEVACIONES': None,
    'PECHO': '15',
    'REMO 1BB': '10',
    'REMO POLEA': '6',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Masino Sofi',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Menendez Adriana',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Miglioranza Cesar',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Miglioranza Eva',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Milito Vicky',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '20',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Molinari Ceci',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Morosini Blas',
    {'CUADRICEPS': '8',
    'DORSALES': '8',
    'ELEVACIONES': '30',
    'PECHO': '20',
    'REMO 1BB': '10',
    'REMO POLEA': '8',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '5'}),
    ('Negri Gaspar',
    {'CUADRICEPS': '3',
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '12,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Nicastro Monica',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': 'rusa',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Nicosia Albert',
    {'CUADRICEPS': '9',
    'DORSALES': '6',
    'ELEVACIONES': '25',
    'PECHO': '12',
    'REMO 1BB': '7,5',
    'REMO POLEA': '7',
    'SENTADILLAS': '12',
    'SUMO': '10',
    'TRICEPS POLEA': '5'}),
    ('Nievas Vir',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Noriega Cristian',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '20',
    'PECHO': '12',
    'REMO 1BB': '5',
    'REMO POLEA': '6',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Oberti Marcelo',
    {'CUADRICEPS': '2',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Oberti Valen',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Orellano Caro',
    {'CUADRICEPS': None,
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '7,5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Pacheco Oli',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Papaleo Cele',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Parodi Coni',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Parra Andres',
    {'CUADRICEPS': '5',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '10',
    'REMO 1BB': '6',
    'REMO POLEA': '4',
    'SENTADILLAS': '12',
    'SUMO': '5',
    'TRICEPS POLEA': '5'}),
    ('Parra Diego',
    {'CUADRICEPS': '5',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '20',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '5',
    'SUMO': '10',
    'TRICEPS POLEA': '5'}),
    ('Pascarelli Marce',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': 'rusa',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Paton Ana',
    {'CUADRICEPS': '8',
    'DORSALES': '4',
    'ELEVACIONES': '30',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '12',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Paz Lujan',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Pellgrini Cami',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7',
    'SUMO': '15',
    'TRICEPS POLEA': '3'}),
    ('Peña Cata',
    {'CUADRICEPS': '5',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Peralta Jorgelina',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Perez Mariana',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Pisonero Mari',
    {'CUADRICEPS': '5',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Platon Ana',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '30',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '12',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Ponti Belen',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '2,5',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '2'}),
    ('Poza Luli',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Poza Rodrigo',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Priano Pau',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': 'barra',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Puyos Carla',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Quevedo yani',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '25',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '20',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Ravena Ana',
    {'CUADRICEPS': '6',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '17',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Redondo Moni',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Reynoso Vanesa',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': '5',
    'PECHO': '1',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Rocha Daniel',
    {'CUADRICEPS': '7',
    'DORSALES': '5',
    'ELEVACIONES': '5',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Rocha Ricardo',
    {'CUADRICEPS': '3',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Rodriguez Ana',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Rodriguez Juli',
    {'CUADRICEPS': '8',
    'DORSALES': '8',
    'ELEVACIONES': '35',
    'PECHO': '20',
    'REMO 1BB': '10',
    'REMO POLEA': '8',
    'SENTADILLAS': '20',
    'SUMO': '10',
    'TRICEPS POLEA': '6'}),
    ('Romanello Ceci',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Rosso Marcela',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Salinas Fausto',
    {'CUADRICEPS': '1',
    'DORSALES': '1',
    'ELEVACIONES': None,
    'PECHO': 'barra',
    'REMO 1BB': '2,5',
    'REMO POLEA': '1',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '1'}),
    ('Salinas Pablo',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Sanchez maria del carmen',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': 'disco',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Santiago Sil',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Sartor Soledad',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': 'barra',
    'TRICEPS POLEA': '3'}),
    ('Scardulla Wendy',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Scarnatto Marco',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Segura Carlos',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Sela Pablo',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': None,
    'PECHO': '10',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '10',
    'SUMO': None,
    'TRICEPS POLEA': '4'}),
    ('Silva Ana',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Sinisi Nati',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Solari Sofi',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Somma Juli',
    {'CUADRICEPS': '8',
    'DORSALES': '5',
    'ELEVACIONES': '25',
    'PECHO': '10',
    'REMO 1BB': '7,5',
    'REMO POLEA': '6',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Sosa Rosana',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '7,5',
    'REMO 1BB': '4',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Soto Claudio',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Spindola Gabriela',
    {'CUADRICEPS': '5',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Suarez Santino',
    {'CUADRICEPS': '6',
    'DORSALES': '6',
    'ELEVACIONES': '25',
    'PECHO': '12',
    'REMO 1BB': '7,5',
    'REMO POLEA': '6',
    'SENTADILLAS': '15',
    'SUMO': '10',
    'TRICEPS POLEA': '4'}),
    ('Tiberi Alberto',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Tiberi Sergio',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Tomas Pia',
    {'CUADRICEPS': '4',
    'DORSALES': '3',
    'ELEVACIONES': '10',
    'PECHO': '5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Torres Aldo (tobi)',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '10',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '5',
    'SUMO': '5',
    'TRICEPS POLEA': '4'}),
    ('Torres Erica',
    {'CUADRICEPS': '3',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '2,5',
    'REMO 1BB': '4',
    'REMO POLEA': '4',
    'SENTADILLAS': '10',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('Tourn Dalila',
    {'CUADRICEPS': '8',
    'DORSALES': '5',
    'ELEVACIONES': '35',
    'PECHO': '12',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '22',
    'SUMO': '15',
    'TRICEPS POLEA': '4'}),
    ('Valldosera Caro',
    {'CUADRICEPS': '8',
    'DORSALES': '5',
    'ELEVACIONES': '30',
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '5',
    'SENTADILLAS': '20',
    'SUMO': '15',
    'TRICEPS POLEA': '4'}),
    ('Vigione Ana',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '5',
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Vilches Daniel',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Vilches Estefnia',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Vitale beto',
    {'CUADRICEPS': '2',
    'DORSALES': '3',
    'ELEVACIONES': None,
    'PECHO': '7,5',
    'REMO 1BB': '5',
    'REMO POLEA': '3',
    'SENTADILLAS': '7,5',
    'SUMO': None,
    'TRICEPS POLEA': '3'}),
    ('Vitale Milagros',
    {'CUADRICEPS': '3',
    'DORSALES': '3',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '3',
    'SENTADILLAS': '10',
    'SUMO': '5',
    'TRICEPS POLEA': '3'}),
    ('Zafalon Mica',
    {'CUADRICEPS': '2',
    'DORSALES': '2',
    'ELEVACIONES': None,
    'PECHO': '2,5',
    'REMO 1BB': '2,5',
    'REMO POLEA': '2',
    'SENTADILLAS': '2,5',
    'SUMO': None,
    'TRICEPS POLEA': '2'}),
    ('Zeppa Delfi',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Zeppa Ernes',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': '5',
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('Zeppa Vicky',
    {'CUADRICEPS': '4',
    'DORSALES': '4',
    'ELEVACIONES': '15',
    'PECHO': '5',
    'REMO 1BB': '5',
    'REMO POLEA': '4',
    'SENTADILLAS': '5',
    'SUMO': '10',
    'TRICEPS POLEA': '3'}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': None,
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None}),
    ('nan',
    {'CUADRICEPS': None,
    'DORSALES': None,
    'ELEVACIONES': None,
    'PECHO': None,
    'REMO 1BB': None,
    'REMO POLEA': '',
    'SENTADILLAS': None,
    'SUMO': None,
    'TRICEPS POLEA': None})]

    for socio_nombre_completo, ejercicios_pesos in SOCIOS_Y_PESOS:
        partes = socio_nombre_completo.split(' ', 1)
        if len(partes) == 2:
            apellido, nombre = partes
        else:
            apellido, nombre = partes[0], ''

        apellido = apellido.strip().capitalize()
        nombre = nombre.strip().capitalize()

        try:
            socio = Socio.objects.get(nombre__iexact=nombre, apellido__iexact=apellido)
        except Socio.DoesNotExist:
            print(f"⚠️ Socio no encontrado: '{apellido} {nombre}'")
            continue

        for ejercicio_nombre, peso_raw in ejercicios_pesos.items():
            if peso_raw == "-" or peso_raw is None:
                continue  # Ignorar valores vacíos o guiones

            # Intentar limpiar el valor
            try:
                peso_str = str(peso_raw).lower().replace("kg", "").replace(",", ".").strip()
                peso = Decimal(peso_str)
            except (InvalidOperation, ValueError):
                print(f"⚠️ Peso inválido para {socio}: {peso_raw} en ejercicio {ejercicio_nombre}")
                continue

            ejercicio = ejercicios_objetos.get(ejercicio_nombre)
            if not ejercicio:
                print(f"⚠️ Ejercicio no encontrado: {ejercicio_nombre}")
                continue

            RegistroEjercicio.objects.create(
                socio=socio,
                ejercicio=ejercicio,
                fecha=hoy,
                peso=peso
            )
            print(f"✔️ Registro creado: {socio} - {ejercicio} - {peso} kg")

def revertir_carga(apps, schema_editor):
    RegistroEjercicio = apps.get_model('ejercicios', 'RegistroEjercicio')
    RegistroEjercicio.objects.filter(fecha=date.today()).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_populate_observaciones'),
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_ejercicios_y_registros, revertir_carga),
    ]
