# Generated by Django 5.2 on 2025-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
