# Generated by Django 5.2 on 2025-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_observacion_delete_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='dni',
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
