# Generated by Django 5.2 on 2025-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='dias_por_semana',
            field=models.IntegerField(default=0),
        ),
    ]
